name: Deploy to Codeberg Pages
on:
  push:
    branches: [main]
    paths: ['site_src/**', 'website/**']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: codeberg-tiny
    container:
      image: alpine:edge
    steps:
      - name: Install prerequisites
        run: |
          echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          apk update
          apk add --no-cache nodejs make lowdown
          apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing sblg

      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Build site
        working-directory: website
        run: make install PAGES_SRC_DIR=site_src

      - name: Deploy canonical (kewplayer.com)
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://${{ forge.repository_owner }}.codeberg.page/kew/'
          token: ${{ forge.token }}
          source: pages/

      - name: Prep redirect-only site
        run: |
          mkdir -p redirect_only
          echo '//www.kewplayer.com/* https://kewplayer.com/:splat 302!' > redirect_only/_redirects
          echo '//kewplayer.org/* https://kewplayer.com/:splat 302!' >> redirect_only/_redirects
          echo '//www.kewplayer.org/* https://kewplayer.com/:splat 302!' >> redirect_only/_redirects

      - name: Deploy redirect (www.kewplayer.com)
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://www.kewplayer.com/'
          token: ${{ forge.token }}
          source: redirect_only/

      - name: Deploy redirect (kewplayer.org)
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://kewplayer.org/'
          token: ${{ forge.token }}
          source: redirect_only/

      - name: Deploy redirect (www.kewplayer.org)
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://www.kewplayer.org/'
          token: ${{ forge.token }}
          source: redirect_only/

permissions:
  contents: write
