.Dd 9/3/23               \" DATE
.Dt kew 1      \" Program name and manual section number
.Os Linux
.Sh NAME                 \" Section Header - required - don't modify
.Nm kew
,
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line.
.Nm kew music command
.\" Use .Nm macro to designate other names for the documented program.
.Nd A terminal music player.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op OPTIONS              \"
.Op Ar PARTIAL FILE OR DIRECTORY NAME              \" [file]
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
plays audio from your music folder when given a partial (or whole) file or directory name.
A playlist is created when finding more than one file.
It supports gapless playback, 24-bit/192khz audio and MPRIS.
.Pp

On first use, set a path for the music library (this is a once-only operation):
.Bl
.It
.Nm
path "/home/joe/Music"
.El
.Pp
Typical use:
.Bl
.It
.Nm
artist, album or song name
.El
.Pp
.Nm
returns results from the location of the first match, it doesn't return every result possible.
.Pp
.Sh OPTIONS
.Pp
.Bl -tag -width -indent
.It Fl h, -help
Displays help.
.It Fl v, -version
Displays version info.
.It Fl -nocover
Hides the cover.
.It Fl -noui
Completely hides the UI.
.It Fl q, --quitonstop
Exits after playing the whole playlist.
.It Fl e, --exact
Specifies you want an exact (but not case sensitive) match, of for instance an album.
.It shuffle
Shuffles the playlist before starting to play it.
.It dir
Plays the directory not the song.
.It song
Plays the song not the directory.
.It list
Searches for a (.m3u) playlist. These are normally not included in searches.
.El
.Sh EXAMPLES
.Pp
.Bl -tag -width -indent
.It kew
Start
.Nm
in library view.
.It kew all
Start
.Nm
with all songs loaded into a playlist.
.It kew albums
Start
.Nm
with all albums randomly added one after the other in the playlist.
.It kew moonlight son
Play moonlight sonata.
.It kew moon
Play moonlight sonata.
.It kew nirv
Play all music under Nirvana folder shuffled.
.It kew neverm
Play Nevermind album in alphabetical order.
.It kew shuffle neverm
Play Nevermind album shuffled.
.It kew list mix
Play the mix.m3u playlist.
.It kew <words A>:<words B>:<words C>
Play the first match (whole directory or file) found under A, B, and C, shuffled. Searches are separated by a colon ':' character.
.It "kew ."
Play the kew.m3u playlist.
.El                      \" Ends the list
.Sh KEY BINDINGS
.Pp
.Bl -tag -width -indent
.It +, -
Adjusts volume.
.It Left-right arrows/h,l
Change song.
.It Space
Pause.
.It F2 or Shift+z
Show playlist view
.It F3 or Shift+x
Show library view
.It F4 or Shift+c
Show track view
.It F5 or Shift+v
Show search view
.It F6 or Shift+b
Show radio search view.
.It F7 or Shift+n
Show key bindings view
.It u
Update the libarary.
.It i
Toggle colors derived from album cover or from color theme.
.It v
Toggle spectrum visualizer.
.It b
Switch between ascii and image album cover.
.It r
Repeat current song after playing.
.It s
Shuffles the playlist.
.It a
Seek Backward.
.It d
Seek Forward.
.It "."
Add to kew.m3u playlist. Run with "kew .".
.It x
Save currently loaded playlist to a .m3u file in the music folder.
.It Tab
Switch to next view.
.It Shift+Tab
Switch to previous view.
.It Backspace
Clear the playlist.
.It Delete
Remove a single playlist entry.
.It t,g
Move a song up or down the playlist.
.It number + G or Enter
Go to specific song number in the playlist.
.It G
Go to last song.
.It Esc or q
Quit
.Nm .
.El
.Sh FILES
.Bl -tag -width -compact
.It Pa "~/<configfolder>/kewrc"
Config file.
.It Pa "~/<configfolder>/kew/kewlibrary"
Music library directory tree cache.
.It Pa "/<musicfolder>/kew.m3u"
The
.Nm
playlist. Add to it by pressing '.' during playback of any song. This playlist is saved before q exits.
.El
.Sh COPYRIGHT
Copyright © 2023 Ravachol. License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.Sh SEE ALSO
.Bl -tag -width -compact
Project home page:
.It Pa <https://github.com/ravachol/kew>.
.El                      \" Ends the list
